name: Run pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --no-root
      - name: Run pylint
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src 
          poetry run pylint $(git ls-files '*.py')           
