name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --no-root
      - name: Run unit tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src 
          poetry run pytest tests/unit/            
